COMRS-183 -Added metadata sharing package for 'FICHE DU PATIENT AVEC VIH - ENFANT' form
jembi/cameroon-bahmni-metadata pull request #15
Opened 2019-03-14 12:42 UTC by rubailly

2019-03-14 14:41 UTC, tmvumbi requested changes
@rubailly the import of the zip is failing, below are some insights from the logs: 
```
ERROR - InitializerServiceImpl.importMetadataSharingPackages(160) |2019-03-14 13:27:50,632| The MDS package could not be imported: /opt/openmrs/configuration/metadatasharing/ConceptsForFormChildPatientWithHiv-1.zip
...
Caused by: org.openmrs.api.db.DAOException: Error saving org.openmrs.Concept [a2065636-5326-40f5-aed6-0cc2cca81ccc]
...
Caused by: org.openmrs.api.APIException: Cannot save Concept #2146. Failed with the following exception:
...
Caused by: org.openmrs.api.DuplicateConceptNameException: 'Oui' is a duplicate name in locale 'fr'
```

2019-03-14 14:41 UTC, tmvumbi commented on .gitignore
> +*.class
@rubailly the .gitignore below is used for java projects. The metadata repo will only contain config files (that we add manually); the files ignored here are artifacts created during the java build process (which won't happen for this repo). I think we can safely remove the .gitignore for the metadata repo.

2019-03-14 14:43 UTC, tmvumbi requested changes
@rubailly the import of the zip is failing, below are some insights from the logs: 
```
ERROR - InitializerServiceImpl.importMetadataSharingPackages(160) |2019-03-14 13:27:50,632| The MDS package could not be imported: /opt/openmrs/configuration/metadatasharing/ConceptsForFormChildPatientWithHiv-1.zip
...
Caused by: org.openmrs.api.db.DAOException: Error saving org.openmrs.Concept [a2065636-5326-40f5-aed6-0cc2cca81ccc]
...
Caused by: org.openmrs.api.APIException: Cannot save Concept #2146. Failed with the following exception:
...
Caused by: org.openmrs.api.DuplicateConceptNameException: 'Oui' is a duplicate name in locale 'fr'
```

2019-03-18 07:26 UTC, rubailly commented on .gitignore
> +*.class
@tmvumbi -how do you clone and make changes tho the files/folders of this repo? Me, I cloned it into Eclipse like I do with other projects and made my changes. I assume others will also try the same, like cloning the project with IntelliJ and adding their changes. 

You end-up having files like .**cproject**  which you don't want to push. We can maybe cleanup the .gitingore file and remove all the unnecessary lines, but have at list IDE related lines remain.
Unless we assume no one will ever use an IDE to work on this repo 😀

2019-03-26 12:12 UTC, closed without merging