COMRS-66: Internationalization of Location Button
jembi/cameroon-bahmni-metadata pull request #2
Opened 2019-02-21 11:53 UTC by prashantsable1991

Internationalization of Location Button
JIRA Card: https://jembiprojects.jira.com/browse/COMRS-66

2019-02-22 13:14 UTC, tmvumbi2 requested changes
Thanks @prashantsable1991, the location import worked well. I left a feedback regarding some small differences between the original location hierarchy and the import result

2019-02-22 13:14 UTC, tmvumbi2 commented on configuration/locations/locations.csv
> +Uuid,Void/Retire,Name,Description,Parent,Tags,Address 1,Address 2,Address 3,Address 4,Address 5,Address 6,City/Village,County/District,State/Province,Postal Code,Country,_order:1000
@prashantsable1991 there are some small differences between the original location hierarchy structure and the imported structure:
- HOME_LOCATION_LABOR_WARD should be under HOME_LOCATION_MATERNITY
- HOME_LOCATION_PEDIATRIC should be under HOME_LOCATION_SPECIALIZED_CONSULTATIONS
- Subcenter 1, 2 and 3 should be voided/retired
- The tree starting from 'Ganiyari' should to be removed (or voided if it can't be removed through configuration)
- Unknown Location should be removed (or voided if it can't be removed through configuration)

Could you also please double check in case I forgot something?

Original location hierarchy:
![image](https://user-images.githubusercontent.com/22587098/53242856-b1666d00-36ae-11e9-9d72-668aea7bf203.png)


Imported location hierarchy:
![image](https://user-images.githubusercontent.com/22587098/53242871-bfb48900-36ae-11e9-935a-f2c3e60cfc38.png)

2019-02-25 16:10 UTC, prashantsable1991 commented on configuration/locations/locations.csv
> +Uuid,Void/Retire,Name,Description,Parent,Tags,Address 1,Address 2,Address 3,Address 4,Address 5,Address 6,City/Village,County/District,State/Province,Postal Code,Country,_order:1000
Pushed updated location.csv

2019-02-26 13:04 UTC, tmvumbi2 approved these changes

2019-02-26 13:05 UTC, merged