COM-172 Update Program labels
jembi/cameroon-bahmni-metadata pull request #38
Opened 2019-04-18 07:45 UTC by prashantsable1991

Added SQL files to change program labels using database.

2019-04-23 14:27 UTC, tmvumbi2 submitted a review, later dismissed

2019-04-23 14:45 UTC, tmvumbi2 commented
The data type for `PROGRAM_MANAGEMENT_ART_NUMBER` needs to be `org.openmrs.customdatatype.datatype.FreeTextDatatype`, and `datatype_config` should be null

![image](https://user-images.githubusercontent.com/22587098/56590242-0e1ad100-65e7-11e9-89dd-863646d0c8bf.png)

2019-04-23 14:47 UTC, tmvumbi2 requested changes
Thanks for the PR @prashantsable1991, the updates worked fine. We just also need to make PROGRAM_MANAGEMENT_ART_NUMBER free text, please see the above feedback

2019-04-24 06:26 UTC, prashantsable1991 commented
Thanks for comment Tresor I have made changes as per suggestions. Please have a look.

2019-04-24 06:52 UTC, merged