COM-193 Update list of HIV ARV regimen
jembi/cameroon-bahmni-metadata pull request #46
Opened 2019-04-30 07:14 UTC by IipperMangesh

Added Concepts and Drugs in metadata sharing for all indicators.

2019-04-30 08:08 UTC, tmvumbi2 commented
@IipperMangesh could you perhaps use a more specific name for the concept csv file? I think something like `drugs.csv` will do

2019-04-30 08:35 UTC, tmvumbi2 requested changes

2019-04-30 08:35 UTC, tmvumbi2 commented on configuration/concepts/concepts_base.csv
> +Uuid,Void/Retire,Fully specified name:en,Fully specified name:fr,Short name:en,Short name:fr,Description:en,Description:fr,Data class,Data type,_version:1,_order:1000
@IipperMangesh there is no value populated for the column `Void/Retire`; if the default value is 'false`, could you please check if it's possible not to include this column entirely?

2019-04-30 08:35 UTC, tmvumbi2 commented on configuration/concepts/concepts_base.csv
> +0aca2d79-1a16-42c8-b2c0-a4989bd55aec,,AZT+3TC+ATZ/r,,AZT+3TC+ATZ/r,,AZT+3TC+ATZ/r,,Drug,N/A,,
@IipperMangesh the import failed on the above concept (see below the error message from the log); I suspect this is due to the double commas

`
ERROR - CsvParser.saveAll(184) |2019-04-30 07:44:09,986| An OpenMRS object could not be constructed or saved from the following CSV line: [0aca2d79-1a16-42c8-b2c0-a4989bd55aec, null, AZT+3TC+ATZ/r, null, AZT+3TC+ATZ/r, null, AZT+3TC+ATZ/r, null, Drug, N/A, null, null]
`

2019-04-30 08:35 UTC, tmvumbi2 commented on configuration/concepts/concepts_base.csv
> +48728efa-b311-4696-a8d0-f2bc155ccd35,,ABC+3TC+ATZ/r ,,ABC+3TC+ATZ/r ,,ABC+3TC+ATZ/r ,,Drug,N/A,,
@IipperMangesh Please ensure that there is no trailing space after the concept's name. Could you please also trim the concept names on the lines below as well?

2019-04-30 08:35 UTC, tmvumbi2 commented on configuration/concepts/concepts_base.csv
> +66e89a39-4aa8-4d8b-b7b2-704fc678bc25,,AZT/3TC+EFV,,AZT/3TC+EFV,,AZT/3TC+EFV,,Drug,N/A,,
@IipperMangesh This drug exists already in the current dev box and it has a concept associated with it.
The drugs from line 9 to 15 also exist already

2019-04-30 08:35 UTC, tmvumbi2 commented on configuration/concepts/concepts_base.csv
> +0aca2d79-1a16-42c8-b2c0-a4989bd55aec,,AZT+3TC+ATZ/r,,AZT+3TC+ATZ/r,,AZT+3TC+ATZ/r,,Drug,N/A,,
@IipperMangesh the concept names should be repeated 4 times on each row (full specified name in fr and en, and short name in fr and en); they are currently repeated 3 times

2019-04-30 08:41 UTC, tmvumbi2 commented
@IipperMangesh please note the following requirement from the ticket

![image](https://user-images.githubusercontent.com/22587098/56949875-5f214c80-6b34-11e9-8a9d-2e7545299ee0.png)

2019-05-08 10:36 UTC, prashantsable1991 commented
As discussed with @IipperMangesh I only checked for newly created drugs. And new drugs are adding properly.

2019-05-08 10:36 UTC, merged